version: '3.8'

services:

  db:
    image: postgres:latest
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: XX:$DB_USER
      POSTGRES_PASSWORD: XX:$DB_PASSWORD
      POSTGRES_DB: ff4j
    networks:
      - ff4j-network
  redis:
    image: redis:latest
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - cache:/data
    networks:
      - ff4j-network
  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
        - ff4j-network

networks:
  ff4j-network:
    driver: bridge
volumes:
  cache:
    driver: local