spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ff4j
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      allow-pool-suspension: true
      connection-timeout: 30000
      validation-timeout: 5000
      connection-test-query: select 1
      leak-detection-threshold: 90000
      maximum-pool-size: 10
      minimum-idle: 1
      pool-name: ${spring.application.name}
  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    locations: classpath:db/migration
    baseline-on-migrate: true
    validate-on-migrate: true
    create-schemas: true
    default-schema: flyway
  application:
    name: ff4j-spring-boot
ff4j:
  api:
    context-path: /api/v1/ff4j     # default '/api/ff4j'
    spring-doc:
      enabled: true
  audit:
    enabled: true
  web-console:
    context-path: /ff4j-web-console       # default '/ff4j-web-console'
    enabled: true
  cache:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    root: info