-- Main Table to store Features
CREATE TABLE IF NOT EXISTS public.FF4J_FEATURES  (
    FEAT_UID VARCHAR(100),
    ENABLE INTEGER NOT NULL,
    DESCRIPTION VARCHAR(255),
    STRATEGY VARCHAR(255),
    EXPRESSION VARCHAR(255),
    GROUPNAME VARCHAR(255),
    PRIMARY KEY(FEAT_UID)
    );
