
CREATE TABLE  IF NOT EXISTS public.FF4J_PROPERTIES (
    PROPERTY_ID  VARCHAR(100) NOT NULL,
    CLAZZ        VARCHAR(255) NOT NULL,
    CURRENTVALUE VARCHAR(255),
    FIXEDVALUES  VARCHAR(1000),
    DESCRIPTION  VARCHAR(1000),
    PRIMARY KEY(PROPERTY_ID)
    );
